# Site settings
title: Kristen's Blog
description: "This is a blog of everything that is important to Kristen - programming, zumba, food"
baseurl: ""
url: kristen.github.io
github: kristen
paginate: 5

# Build settings
markdown: kramdown
permalink: pretty
