# Site settings
title: Kristen's Blog
email: kssundquist@gmail.com
description: "This is a blog of everything that is important to Kristen - programming, zumba, food"
baseurl: ""
url: kristen.github.io
github: kristen
twitter: ksunkisd
paginate: 5

# Build settings
markdown: kramdown
permalink: pretty
